### ISSUE TITLE
Fails to build on Ubuntu 22.04 due to catch2

### ISSUE THREAD

**Issue by true2thepen** [UnicycleBloke/yagl#4]
![Screenshot_20230525_070324](https://github.com/UnicycleBloke/yagl/assets/25501927/83c5c250-5675-4acb-94e1-4734c6be2512)

Upgrading catch2 to version 3.3.2 solves this.

In version 3.3.2 the header file is named catch_amalgamated.hpp. I simply renamed it to catch.hpp and overwrote the file in third_party/catch2/. It then builds without any problems.

Test run of yagl  works as expected.

**Comment by UnicycleBloke** [comment]
Thank you for the heads up. I believe I have resolved this. There were issues with Catch2 declaring its own main() which I fixed by splitting the tests into a separate application (should have done this originally). I have tested the build in Ubuntu 22.04, WSL and Windows. Please let me know if there are further issues.
